import Container from "@/components/shared/container";
import Footer from "@/components/shared/footer";
import { Header } from "@/components/shared/header";
import ThemeProvider from "@/context/theme-provider";
import { getGlobalSettings } from "@/data/loaders";
import { CssBaseline } from "@mui/material";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getGlobalData() {
  const { data } = await getGlobalSettings();
  if (!data) throw new Error("Failed to fetch global settings");
  return { header: data?.header, footer: data?.footer };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { header, footer } = await getGlobalData();

  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider>
            <CssBaseline />
            <Header {...header} />
            <Container>{children}</Container>
            <Footer {...footer} />
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
